import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import Header from "@/components/Header";

import ClientSessionProvider from "@/components/ClientSessionProvider";
import Footer from "@/components/Footer";
import { AppProvider } from "@/context/AppProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased h-screen font-sans">
        <ClientSessionProvider>
          <AppProvider>
            <Toaster position="top-center" richColors />
            <Header />
            <main>{children}</main>
            <Footer />
          </AppProvider>
        </ClientSessionProvider>
      </body>
    </html>
  );
}
